title: Jito Restaking Documentation
longtitle: Jito Restaking Documentation
description: Jito Restaking Documentation
remote_theme: sighingnow/jekyll-gitbook

syntax_highlighter_style: colorful

collections:
  pages:
    output: true
ordered_collections:
  - pages