remote_theme: sighingnow/jekyll-gitbook
title: BODS for Linked Data
description: The Beneficial Ownership Data Standard v0.4 RDF data model
baseurl: '/'
syntax_highlighter_style: colorful

collections:
  pages:
    output: true
ordered_collections:
  - pages

toc:
  enabled: true