remote_theme: sighingnow/jekyll-gitbook
title: Leetcode Solutions
baseurl: '/'
github_username: jithset
syntax_highlighter_style: github
collections:
  pages:
    output: true
    permalink: /:collection/:path/
ordered_collections:
  - pages

